# Generated by Django 4.1.4 on 2022-12-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('LATE', 'LATE'), ('ON_TIME', 'ON_TIME'), ('CANCELLED', 'CANCELLED'), ('ARRIVED', 'ARRIVED')], max_length=30)),
            ],
        ),
    ]
